add more ways to modify a block
mythicmc/EditStick pull request #1
Opened 2021-08-13 15:43 UTC by M0rv1n

2021-08-16 10:46 UTC, retrixe requested changes
These are the first bits I'd like to get cleaned up before discussing the actual code.

2021-08-16 10:46 UTC, retrixe commented on src/main/java/org/mythicmc/editstick/listener/PlayerInteractListener.java
> +                    if(EditStickUtils.canBuild(p, location)){
Code style doesn't fit.
```suggestion
                    if (EditStickUtils.canBuild(p, location)) {
```

2021-08-16 10:46 UTC, retrixe commented on src/main/java/org/mythicmc/editstick/listener/PlayerInteractListener.java
> +        else if (e.getAction() == Action.LEFT_CLICK_BLOCK) {
Convert the first `if` into `e.getAction() == Action.LEFT_CLICK_BLOCK || e.getAction() == Action.RIGHT_CLICK_BLOCK` and remove this entire if condition.

Then change `BlockUtils.rotateBlock(block);` to:
```java
                        if (e.getAction() == Action.RIGHT_CLICK_BLOCK) {
                            BlockUtils.rotateBlock(block);
                        } else BlockUtils.changeHalf(block);
```

2021-08-16 10:46 UTC, retrixe commented on src/main/java/org/mythicmc/editstick/util/BlockUtils.java
> +            block.setBlockData(bisect);
This needs to be an else-if, also did some stylistic changes.
```suggestion
        if (blockData instanceof Slab) {
            Slab slab = (Slab) blockData;
            Slab.Type type = slab.getType();
            if (type == Slab.Type.BOTTOM) {
                slab.setType(Slab.Type.TOP);
            } else if (type == Slab.Type.TOP)
                slab.setType(Slab.Type.BOTTOM);
            }
            block.setBlockData(slab);
        } else if (blockData instanceof Bisected) {
            Bisected bisect = (Bisected) blockData;
            Bisected.Half half = bisect.getHalf();
            if (half == Bisected.Half.TOP) {
                bisect.setHalf(Bisected.Half.BOTTOM);
            } else if (half == Bisected.Half.BOTTOM) {
                bisect.setHalf(Bisected.Half.TOP);
            }
            block.setBlockData(bisect);
```

2021-08-16 10:46 UTC, retrixe commented on src/main/java/org/mythicmc/editstick/util/BlockUtils.java
> +                if(directional.getFaces().contains(BlockFace.UP)){
Slight stylistic change.
```suggestion
                if (directional.getFaces().contains(BlockFace.UP)) {
```

2021-08-16 10:46 UTC, retrixe commented on src/main/java/org/mythicmc/editstick/util/BlockUtils.java
> +            } else if(face == BlockFace.DOWN){
```suggestion
            } else if (face == BlockFace.UP) {
                directional.setFacing(BlockFace.DOWN);
            } else if (face == BlockFace.DOWN) {
```

2021-08-16 12:38 UTC, retrixe reviewed
This PR just needs to be tested, send me a JAR over Discord and I can test this in action.

2021-08-16 12:38 UTC, retrixe commented on src/main/java/org/mythicmc/editstick/util/BlockUtils.java
> +                directional.setFacing((BlockFace.NORTH));
How does this work? Does this cycle through 6 orientations instead of 4 by making the block face up/down?

2021-08-16 12:38 UTC, retrixe commented on src/main/java/org/mythicmc/editstick/util/BlockUtils.java
> +        else if (blockData instanceof Orientable) {
Is any block both Orientable and Directional?

2021-08-16 13:23 UTC, M0rv1n commented on src/main/java/org/mythicmc/editstick/util/BlockUtils.java
> +                directional.setFacing((BlockFace.NORTH));
`getFaces()` returns a set of all possible faces for that block, If that block can face up/down then yes, It'll cycle through all 6 of them. Else it'll just cycle through 4 of those.

2021-08-16 14:39 UTC, M0rv1n commented on src/main/java/org/mythicmc/editstick/util/BlockUtils.java
> +        else if (blockData instanceof Orientable) {
Not sure about this one, though Directional will be the priority in that case. So it shouldn't be a problem.

2021-08-16 18:01 UTC, retrixe requested changes
Use Java 16 `instanceof` pattern matching and disable reorientation for double chests and beds and bisection for doors.

2021-08-16 18:01 UTC, retrixe commented on src/main/java/org/mythicmc/editstick/util/BlockUtils.java
> +            Slab slab = (Slab) blockData;
```suggestion
        if (blockData instanceof Slab slab) {
```

2021-08-16 18:01 UTC, retrixe commented on src/main/java/org/mythicmc/editstick/util/BlockUtils.java
> +            Bisected bisect = (Bisected) blockData;
```suggestion
        } else if (blockData instanceof Bisected bisect) {
```

2021-08-16 18:01 UTC, retrixe commented on src/main/java/org/mythicmc/editstick/util/BlockUtils.java
> +            Orientable orientation = (Orientable) blockData;
```suggestion
        else if (blockData instanceof Orientable orientation) {
```

2021-08-16 18:01 UTC, retrixe commented on src/main/java/org/mythicmc/editstick/util/BlockUtils.java
>              Directional directional = (Directional) blockData;
```suggestion
        if (blockData instanceof Directional directional) {
```

2021-08-19 21:09 UTC, Sanguineous1 approved these changes

2021-08-19 21:14 UTC, retrixe approved these changes

2021-08-19 21:25 UTC, merged